EXPLAIN
CREATE TABLE INPUTDDL2(key INT, value STRING, ds STRING, country STRING)
PARTITION BY list(ds) SUBPARTITION BY list(country)
(SUBPARTITION sp0 VALUES IN ('USA'),
SUBPARTITION sp1 VALUES IN ('CHINA'))
(PARTITION p0 VALUES IN ('2008-01-01'),
PARTITION p1 VALUES IN ('2008-02-01'))
STORED AS TEXTFILE;

CREATE TABLE INPUTDDL2(key INT, value STRING, ds STRING, country STRING)
PARTITION BY list(ds) SUBPARTITION BY list(country)
(SUBPARTITION sp0 VALUES IN ('USA'),
SUBPARTITION sp1 VALUES IN ('CHINA'))
(PARTITION p0 VALUES IN ('2008-01-01'),
PARTITION p1 VALUES IN ('2008-02-01'))
STORED AS TEXTFILE;

DESCRIBE INPUTDDL2;
DROP TABLE INPUTDDL2;

